

/*full call to dissociate or evaluate binding pairs*/
void dissociate_callPBC(int Ntotalmol, Fullmol *bases, Complex *ind_com, Parms &plist, int *p_home, int *i_home, int **Rlist, int *Nmyrxn, int **myrxn, double *bindrad, int *Ncoup, int **mycoupled, double irandmax, int &ndiss, int *disslist, int *ncross, double *kr, int it);
void dissociate_sigmaPBC(int Ntotalmol, Fullmol *bases, Complex *ind_com, Parms &plist, int *p_home, int *i_home, int **Rlist, int *Nmyrxn, int **myrxn, double *bindrad, int *Ncoup, int **mycoupled, double irandmax, int &ndiss, int *disslist, int *ncross, double *kr, int it, int *ncrosscom);
void dissociate_sigmaPBC_com(int Ntotalmol, Fullmol *bases, Complex *ind_com, Parms &plist, int *p_home, int *i_home, int **Rlist, int *Nmyrxn, int **myrxn, double *bindrad, int *Ncoup, int **mycoupled, double irandmax, std::vector<int> &disslist, int *ncross, double *kr, int it, int *ncrosscom, int *movestat);
void dissociate_sigma_com(int Ntotalmol, Fullmol *bases, Complex *ind_com, Parms &plist, int *p_home, int *i_home, int **Rlist, int *Nmyrxn, int **myrxn, double *bindrad, int *Ncoup, int **mycoupled, double irandmax, std::vector<int> &disslist, int *ncross, double *kr, int it, int *ncrosscom, int *movestat, int *nBoundPairs);

void evaluate_binding_pair(int i, int j, Fullmol *bases, Complex *ind_com, Parms &plist, Protein *wholep, int &DDtableindex, int *numpartners, int **Speclist, int *i_home, int *ncross, double **probvec, double *TBLID, double *bindrad, int *nprevpart, int **prevlist, int **prevmyface, int **prevpface, double **prevnorm, int *ncurrpart, int **currlist, int **currmyface, int **currpface, double **ps_prev, double **prevsep, double **currprevnorm, double **currps_prev, double **currprevsep, int **myrxn, double **traj, int **crosspart, int **crossint, int **cross_rxn, double *kr, int it, vector<gsl_matrix *>& contsur, vector<gsl_matrix *>& contnorm, vector<gsl_matrix *>& contpir, int MAXALWTBL, int *ncrosscom);
void evaluate_binding_pair_com(int i, int j, Fullmol *bases, Complex *ind_com, Parms &plist, Protein *wholep, int &DDtableindex, int *numpartners, int **Speclist, int *i_home, int *ncross, double **probvec, double *TBLID, double *bindrad, int *nprevpart, int **prevlist, int **prevmyface, int **prevpface, double **prevnorm, int *ncurrpart, int **currlist, int **currmyface, int **currpface, double **ps_prev, double **prevsep, double **currprevnorm, double **currps_prev, double **currprevsep, int **myrxn, double **traj, int **crosspart, int **crossint, int **cross_rxn, double *kr, int it, vector<gsl_matrix *>& contsur, vector<gsl_matrix *>& contnorm, vector<gsl_matrix *>& contpir, int MAXALWTBL, int *ncrosscom, int *movestat);
void evaluate_binding_pair_comPBC(int i, int j, Fullmol *bases, Complex *ind_com, Parms &plist, Protein *wholep, int &DDtableindex, int *numpartners, int **Speclist, int *i_home, int *ncross, double **probvec, double *TBLID, double *bindrad, int *nprevpart, int **prevlist, int **prevmyface, int **prevpface, double **prevnorm, int *ncurrpart, int **currlist, int **currmyface, int **currpface, double **ps_prev, double **prevsep, double **currprevnorm, double **currps_prev, double **currprevsep, int **myrxn, double **traj, int **crosspart, int **crossint, int **cross_rxn, double *kr, int it, vector<gsl_matrix *>& contsur, vector<gsl_matrix *>& contnorm, vector<gsl_matrix *>& contpir, int MAXALWTBL, int *ncrosscom, int *movestat, double scale_Rmax);
void evaluate_binding_pair_com_DB(int i, int j, Fullmol *bases, Complex *ind_com, Parms &plist, Protein *wholep, int &DDtableindex, int *numpartners, int **Speclist, int *i_home, int *ncross, double **probvec, double *TBLID, double *bindrad, int *nprevpart, int **prevlist, int **prevmyface, int **prevpface, double **prevnorm, int *ncurrpart, int **currlist, int **currmyface, int **currpface, double **ps_prev, double **prevsep, double **currprevnorm, double **currps_prev, double **currprevsep, int **myrxn, double **traj, int **crosspart, int **crossint, int **cross_rxn, double *kr, int it, vector<gsl_matrix *>& contsur, vector<gsl_matrix *>& contnorm, vector<gsl_matrix *>& contpir, int MAXALWTBL, int *ncrosscom, int *movestat);
void evaluate_binding_pair_com_tmp(int i, int j, Fullmol *bases, Complex *ind_com, Parms &plist, Protein *wholep, int &DDtableindex, int *numpartners, int **Speclist, int *i_home, int *ncross, double **probvec, double *TBLID, double *bindrad, int *nprevpart, int **prevlist, int **prevmyface, int **prevpface, double **prevnorm, int *ncurrpart, int **currlist, int **currmyface, int **currpface, double **ps_prev, double **prevsep, double **currprevnorm, double **currps_prev, double **currprevsep, int **myrxn, double **traj, int **crosspart, int **crossint, int **cross_rxn, double *kr, int it, vector<gsl_matrix *>& contsur, vector<gsl_matrix *>& contnorm, vector<gsl_matrix *>& contpir, int MAXALWTBL, int *ncrosscom, int *movestat);
void evaluate_binding_pair_com_noreweight(int i, int j, Fullmol *bases, Complex *ind_com, Parms &plist, Protein *wholep, int &DDtableindex, int *numpartners, int **Speclist, int *i_home, int *ncross, double **probvec, double *TBLID, double *bindrad, int *nprevpart, int **prevlist, int **prevmyface, int **prevpface, double **prevnorm, int *ncurrpart, int **currlist, int **currmyface, int **currpface, double **ps_prev, double **prevsep, double **currprevnorm, double **currps_prev, double **currprevsep, int **myrxn, double **traj, int **crosspart, int **crossint, int **cross_rxn, double *kr, int it, vector<gsl_matrix *>& contsur, vector<gsl_matrix *>& contnorm, vector<gsl_matrix *>& contpir, int MAXALWTBL, int *ncrosscom, int *movestat);
void evaluate_binding_pair_com_NoDeff(int i, int j, Fullmol *bases, Complex *ind_com, Parms &plist, Protein *wholep, int &DDtableindex, int *numpartners, int **Speclist, int *i_home, int *ncross, double **probvec, double *TBLID, double *bindrad, int *nprevpart, int **prevlist, int **prevmyface, int **prevpface, double **prevnorm, int *ncurrpart, int **currlist, int **currmyface, int **currpface, double **ps_prev, double **prevsep, double **currprevnorm, double **currps_prev, double **currprevsep, int **myrxn, double **traj, int **crosspart, int **crossint, int **cross_rxn, double *kr, int it, vector<gsl_matrix *>& contsur, vector<gsl_matrix *>& contnorm, vector<gsl_matrix *>& contpir, int MAXALWTBL, int *ncrosscom, int *movestat);
void evaluate_binding_pair_comPBCCELL(int i, int j, Fullmol *bases, Complex *ind_com, Parms &plist, Protein *wholep, int &DDtableindex, int *numpartners, int **Speclist, int *i_home, int *ncross, double **probvec, double *TBLID, double *bindrad, int *nprevpart, int **prevlist, int **prevmyface, int **prevpface, double **prevnorm, int *ncurrpart, int **currlist, int **currmyface, int **currpface, double **ps_prev, double **prevsep, double **currprevnorm, double **currps_prev, double **currprevsep, int **myrxn, double **traj, int **crosspart, int **crossint, int **cross_rxn, double *kr, int it, vector<gsl_matrix *>& contsur, vector<gsl_matrix *>& contnorm, vector<gsl_matrix *>& contpir, int MAXALWTBL, int *ncrosscom, int *movestat);

